// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buffer.proto

package com.alibaba.datax.protobuf;

import com.alibaba.datax.common.element.Column;
import com.alibaba.datax.common.element.Record;

public final class BufferOuterClass {
  private BufferOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BufferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.datax.protobuf.Buffer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord> 
        getBufferList();
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord getBuffer(int index);
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    int getBufferCount();
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    java.util.List<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder> 
        getBufferOrBuilderList();
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder getBufferOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.alibaba.datax.protobuf.Buffer}
   */
  public static final class Buffer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alibaba.datax.protobuf.Buffer)
      BufferOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Buffer.newBuilder() to construct.
    private Buffer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Buffer() {
      buffer_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Buffer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Buffer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                buffer_ = new java.util.ArrayList<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              buffer_.add(
                  input.readMessage(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          buffer_ = java.util.Collections.unmodifiableList(buffer_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_Buffer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_Buffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.datax.protobuf.BufferOuterClass.Buffer.class, com.alibaba.datax.protobuf.BufferOuterClass.Buffer.Builder.class);
    }

    public static final int BUFFER_FIELD_NUMBER = 1;
    private java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord> buffer_;
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord> getBufferList() {
      return buffer_;
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder> 
        getBufferOrBuilderList() {
      return buffer_;
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    @java.lang.Override
    public int getBufferCount() {
      return buffer_.size();
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    @java.lang.Override
    public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord getBuffer(int index) {
      return buffer_.get(index);
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
     */
    @java.lang.Override
    public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder getBufferOrBuilder(
        int index) {
      return buffer_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < buffer_.size(); i++) {
        output.writeMessage(1, buffer_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < buffer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, buffer_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.datax.protobuf.BufferOuterClass.Buffer)) {
        return super.equals(obj);
      }
      com.alibaba.datax.protobuf.BufferOuterClass.Buffer other = (com.alibaba.datax.protobuf.BufferOuterClass.Buffer) obj;

      if (!getBufferList()
          .equals(other.getBufferList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBufferCount() > 0) {
        hash = (37 * hash) + BUFFER_FIELD_NUMBER;
        hash = (53 * hash) + getBufferList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.datax.protobuf.BufferOuterClass.Buffer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.datax.protobuf.Buffer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.datax.protobuf.Buffer)
        com.alibaba.datax.protobuf.BufferOuterClass.BufferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_Buffer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_Buffer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.datax.protobuf.BufferOuterClass.Buffer.class, com.alibaba.datax.protobuf.BufferOuterClass.Buffer.Builder.class);
      }

      // Construct using com.alibaba.datax.protobuf.BufferOuterClass.Buffer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBufferFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (bufferBuilder_ == null) {
          buffer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          bufferBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_Buffer_descriptor;
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.Buffer getDefaultInstanceForType() {
        return com.alibaba.datax.protobuf.BufferOuterClass.Buffer.getDefaultInstance();
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.Buffer build() {
        com.alibaba.datax.protobuf.BufferOuterClass.Buffer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.Buffer buildPartial() {
        com.alibaba.datax.protobuf.BufferOuterClass.Buffer result = new com.alibaba.datax.protobuf.BufferOuterClass.Buffer(this);
        int from_bitField0_ = bitField0_;
        if (bufferBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            buffer_ = java.util.Collections.unmodifiableList(buffer_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.buffer_ = buffer_;
        } else {
          result.buffer_ = bufferBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.datax.protobuf.BufferOuterClass.Buffer) {
          return mergeFrom((com.alibaba.datax.protobuf.BufferOuterClass.Buffer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.datax.protobuf.BufferOuterClass.Buffer other) {
        if (other == com.alibaba.datax.protobuf.BufferOuterClass.Buffer.getDefaultInstance()) return this;
        if (bufferBuilder_ == null) {
          if (!other.buffer_.isEmpty()) {
            if (buffer_.isEmpty()) {
              buffer_ = other.buffer_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBufferIsMutable();
              buffer_.addAll(other.buffer_);
            }
            onChanged();
          }
        } else {
          if (!other.buffer_.isEmpty()) {
            if (bufferBuilder_.isEmpty()) {
              bufferBuilder_.dispose();
              bufferBuilder_ = null;
              buffer_ = other.buffer_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bufferBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBufferFieldBuilder() : null;
            } else {
              bufferBuilder_.addAllMessages(other.buffer_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.datax.protobuf.BufferOuterClass.Buffer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.datax.protobuf.BufferOuterClass.Buffer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord> buffer_ =
        java.util.Collections.emptyList();
      private void ensureBufferIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          buffer_ = new java.util.ArrayList<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord>(buffer_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder> bufferBuilder_;

      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord> getBufferList() {
        if (bufferBuilder_ == null) {
          return java.util.Collections.unmodifiableList(buffer_);
        } else {
          return bufferBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public int getBufferCount() {
        if (bufferBuilder_ == null) {
          return buffer_.size();
        } else {
          return bufferBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord getBuffer(int index) {
        if (bufferBuilder_ == null) {
          return buffer_.get(index);
        } else {
          return bufferBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder setBuffer(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord value) {
        if (bufferBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBufferIsMutable();
          buffer_.set(index, value);
          onChanged();
        } else {
          bufferBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder setBuffer(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder builderForValue) {
        if (bufferBuilder_ == null) {
          ensureBufferIsMutable();
          buffer_.set(index, builderForValue.build());
          onChanged();
        } else {
          bufferBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder addBuffer(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord value) {
        if (bufferBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBufferIsMutable();
          buffer_.add(value);
          onChanged();
        } else {
          bufferBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder addBuffer(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord value) {
        if (bufferBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBufferIsMutable();
          buffer_.add(index, value);
          onChanged();
        } else {
          bufferBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder addBuffer(
          com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder builderForValue) {
        if (bufferBuilder_ == null) {
          ensureBufferIsMutable();
          buffer_.add(builderForValue.build());
          onChanged();
        } else {
          bufferBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder addBuffer(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder builderForValue) {
        if (bufferBuilder_ == null) {
          ensureBufferIsMutable();
          buffer_.add(index, builderForValue.build());
          onChanged();
        } else {
          bufferBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder addAllBuffer(
          java.lang.Iterable<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord> values) {
        if (bufferBuilder_ == null) {
          ensureBufferIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, buffer_);
          onChanged();
        } else {
          bufferBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder clearBuffer() {
        if (bufferBuilder_ == null) {
          buffer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bufferBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public Builder removeBuffer(int index) {
        if (bufferBuilder_ == null) {
          ensureBufferIsMutable();
          buffer_.remove(index);
          onChanged();
        } else {
          bufferBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder getBufferBuilder(
          int index) {
        return getBufferFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder getBufferOrBuilder(
          int index) {
        if (bufferBuilder_ == null) {
          return buffer_.get(index);  } else {
          return bufferBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public java.util.List<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder> 
           getBufferOrBuilderList() {
        if (bufferBuilder_ != null) {
          return bufferBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(buffer_);
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder addBufferBuilder() {
        return getBufferFieldBuilder().addBuilder(
            com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder addBufferBuilder(
          int index) {
        return getBufferFieldBuilder().addBuilder(
            index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufRecord buffer = 1;</code>
       */
      public java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder> 
           getBufferBuilderList() {
        return getBufferFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder> 
          getBufferFieldBuilder() {
        if (bufferBuilder_ == null) {
          bufferBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder>(
                  buffer_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          buffer_ = null;
        }
        return bufferBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alibaba.datax.protobuf.Buffer)
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.datax.protobuf.Buffer)
    private static final com.alibaba.datax.protobuf.BufferOuterClass.Buffer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.datax.protobuf.BufferOuterClass.Buffer();
    }

    public static com.alibaba.datax.protobuf.BufferOuterClass.Buffer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Buffer>
        PARSER = new com.google.protobuf.AbstractParser<Buffer>() {
      @java.lang.Override
      public Buffer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Buffer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Buffer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Buffer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alibaba.datax.protobuf.BufferOuterClass.Buffer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtobufRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.datax.protobuf.ProtobufRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn> 
        getColumnsList();
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn getColumns(int index);
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    int getColumnsCount();
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    java.util.List<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder> 
        getColumnsOrBuilderList();
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder getColumnsOrBuilder(
        int index);

    /**
     * <code>int32 byteSize = 2;</code>
     * @return The byteSize.
     */
    int getByteSize();

    /**
     * <code>int32 memorySize = 3;</code>
     * @return The memorySize.
     */
    int getMemorySize();
  }
  /**
   * Protobuf type {@code com.alibaba.datax.protobuf.ProtobufRecord}
   */
  public static final class ProtobufRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alibaba.datax.protobuf.ProtobufRecord)
      ProtobufRecordOrBuilder, Record {
  private static final long serialVersionUID = 0L;
    // Use ProtobufRecord.newBuilder() to construct.
    private ProtobufRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtobufRecord() {
      columns_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtobufRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtobufRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                columns_ = new java.util.ArrayList<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn>();
                mutable_bitField0_ |= 0x00000001;
              }
              columns_.add(
                  input.readMessage(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.parser(), extensionRegistry));
              break;
            }
            case 16: {

              byteSize_ = input.readInt32();
              break;
            }
            case 24: {

              memorySize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          columns_ = java.util.Collections.unmodifiableList(columns_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.class, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder.class);
    }

    public static final int COLUMNS_FIELD_NUMBER = 1;
    private java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn> columns_;
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn> getColumnsList() {
      return columns_;
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder> 
        getColumnsOrBuilderList() {
      return columns_;
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    @java.lang.Override
    public int getColumnsCount() {
      return columns_.size();
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    @java.lang.Override
    public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn getColumns(int index) {
      return columns_.get(index);
    }
    /**
     * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
     */
    @java.lang.Override
    public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder getColumnsOrBuilder(
        int index) {
      return columns_.get(index);
    }

    public static final int BYTESIZE_FIELD_NUMBER = 2;
    private int byteSize_;

    @Override
    public void addColumn(Column column) {

    }

    @Override
    public void setColumn(int i, Column column) {

    }

    @Override
    public Column getColumn(int i) {
      return null;
    }

    @Override
    public int getColumnNumber() {
      return 0;
    }

    /**
     * <code>int32 byteSize = 2;</code>
     * @return The byteSize.
     */
    @java.lang.Override
    public int getByteSize() {
      return byteSize_;
    }

    public static final int MEMORYSIZE_FIELD_NUMBER = 3;
    private int memorySize_;
    /**
     * <code>int32 memorySize = 3;</code>
     * @return The memorySize.
     */
    @java.lang.Override
    public int getMemorySize() {
      return memorySize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < columns_.size(); i++) {
        output.writeMessage(1, columns_.get(i));
      }
      if (byteSize_ != 0) {
        output.writeInt32(2, byteSize_);
      }
      if (memorySize_ != 0) {
        output.writeInt32(3, memorySize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < columns_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, columns_.get(i));
      }
      if (byteSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, byteSize_);
      }
      if (memorySize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, memorySize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord)) {
        return super.equals(obj);
      }
      com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord other = (com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord) obj;

      if (!getColumnsList()
          .equals(other.getColumnsList())) return false;
      if (getByteSize()
          != other.getByteSize()) return false;
      if (getMemorySize()
          != other.getMemorySize()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getColumnsCount() > 0) {
        hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
        hash = (53 * hash) + getColumnsList().hashCode();
      }
      hash = (37 * hash) + BYTESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getByteSize();
      hash = (37 * hash) + MEMORYSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getMemorySize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.datax.protobuf.ProtobufRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.datax.protobuf.ProtobufRecord)
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.class, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.Builder.class);
      }

      // Construct using com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getColumnsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (columnsBuilder_ == null) {
          columns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          columnsBuilder_.clear();
        }
        byteSize_ = 0;

        memorySize_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufRecord_descriptor;
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord getDefaultInstanceForType() {
        return com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.getDefaultInstance();
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord build() {
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord buildPartial() {
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord result = new com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord(this);
        int from_bitField0_ = bitField0_;
        if (columnsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            columns_ = java.util.Collections.unmodifiableList(columns_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.columns_ = columns_;
        } else {
          result.columns_ = columnsBuilder_.build();
        }
        result.byteSize_ = byteSize_;
        result.memorySize_ = memorySize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord) {
          return mergeFrom((com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord other) {
        if (other == com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord.getDefaultInstance()) return this;
        if (columnsBuilder_ == null) {
          if (!other.columns_.isEmpty()) {
            if (columns_.isEmpty()) {
              columns_ = other.columns_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureColumnsIsMutable();
              columns_.addAll(other.columns_);
            }
            onChanged();
          }
        } else {
          if (!other.columns_.isEmpty()) {
            if (columnsBuilder_.isEmpty()) {
              columnsBuilder_.dispose();
              columnsBuilder_ = null;
              columns_ = other.columns_;
              bitField0_ = (bitField0_ & ~0x00000001);
              columnsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getColumnsFieldBuilder() : null;
            } else {
              columnsBuilder_.addAllMessages(other.columns_);
            }
          }
        }
        if (other.getByteSize() != 0) {
          setByteSize(other.getByteSize());
        }
        if (other.getMemorySize() != 0) {
          setMemorySize(other.getMemorySize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn> columns_ =
        java.util.Collections.emptyList();
      private void ensureColumnsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          columns_ = new java.util.ArrayList<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn>(columns_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder> columnsBuilder_;

      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn> getColumnsList() {
        if (columnsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(columns_);
        } else {
          return columnsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public int getColumnsCount() {
        if (columnsBuilder_ == null) {
          return columns_.size();
        } else {
          return columnsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn getColumns(int index) {
        if (columnsBuilder_ == null) {
          return columns_.get(index);
        } else {
          return columnsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder setColumns(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn value) {
        if (columnsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnsIsMutable();
          columns_.set(index, value);
          onChanged();
        } else {
          columnsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder setColumns(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder builderForValue) {
        if (columnsBuilder_ == null) {
          ensureColumnsIsMutable();
          columns_.set(index, builderForValue.build());
          onChanged();
        } else {
          columnsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder addColumns(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn value) {
        if (columnsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnsIsMutable();
          columns_.add(value);
          onChanged();
        } else {
          columnsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder addColumns(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn value) {
        if (columnsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnsIsMutable();
          columns_.add(index, value);
          onChanged();
        } else {
          columnsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder addColumns(
          com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder builderForValue) {
        if (columnsBuilder_ == null) {
          ensureColumnsIsMutable();
          columns_.add(builderForValue.build());
          onChanged();
        } else {
          columnsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder addColumns(
          int index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder builderForValue) {
        if (columnsBuilder_ == null) {
          ensureColumnsIsMutable();
          columns_.add(index, builderForValue.build());
          onChanged();
        } else {
          columnsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder addAllColumns(
          java.lang.Iterable<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn> values) {
        if (columnsBuilder_ == null) {
          ensureColumnsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, columns_);
          onChanged();
        } else {
          columnsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder clearColumns() {
        if (columnsBuilder_ == null) {
          columns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          columnsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public Builder removeColumns(int index) {
        if (columnsBuilder_ == null) {
          ensureColumnsIsMutable();
          columns_.remove(index);
          onChanged();
        } else {
          columnsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder getColumnsBuilder(
          int index) {
        return getColumnsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder getColumnsOrBuilder(
          int index) {
        if (columnsBuilder_ == null) {
          return columns_.get(index);  } else {
          return columnsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public java.util.List<? extends com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder> 
           getColumnsOrBuilderList() {
        if (columnsBuilder_ != null) {
          return columnsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(columns_);
        }
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder addColumnsBuilder() {
        return getColumnsFieldBuilder().addBuilder(
            com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder addColumnsBuilder(
          int index) {
        return getColumnsFieldBuilder().addBuilder(
            index, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alibaba.datax.protobuf.ProtobufColumn columns = 1;</code>
       */
      public java.util.List<com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder> 
           getColumnsBuilderList() {
        return getColumnsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder> 
          getColumnsFieldBuilder() {
        if (columnsBuilder_ == null) {
          columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder>(
                  columns_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          columns_ = null;
        }
        return columnsBuilder_;
      }

      private int byteSize_ ;
      /**
       * <code>int32 byteSize = 2;</code>
       * @return The byteSize.
       */
      @java.lang.Override
      public int getByteSize() {
        return byteSize_;
      }
      /**
       * <code>int32 byteSize = 2;</code>
       * @param value The byteSize to set.
       * @return This builder for chaining.
       */
      public Builder setByteSize(int value) {
        
        byteSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 byteSize = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearByteSize() {
        
        byteSize_ = 0;
        onChanged();
        return this;
      }

      private int memorySize_ ;
      /**
       * <code>int32 memorySize = 3;</code>
       * @return The memorySize.
       */
      @java.lang.Override
      public int getMemorySize() {
        return memorySize_;
      }
      /**
       * <code>int32 memorySize = 3;</code>
       * @param value The memorySize to set.
       * @return This builder for chaining.
       */
      public Builder setMemorySize(int value) {
        
        memorySize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 memorySize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemorySize() {
        
        memorySize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alibaba.datax.protobuf.ProtobufRecord)
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.datax.protobuf.ProtobufRecord)
    private static final com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord();
    }

    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufRecord>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufRecord>() {
      @java.lang.Override
      public ProtobufRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtobufRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtobufRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtobufColumnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alibaba.datax.protobuf.ProtobufColumn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
     * @return The type.
     */
    com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType getType();

    /**
     * <code>bytes rawData = 2;</code>
     * @return The rawData.
     */
    com.google.protobuf.ByteString getRawData();

    /**
     * <code>int32 byteSize = 3;</code>
     * @return The byteSize.
     */
    int getByteSize();
  }
  /**
   * Protobuf type {@code com.alibaba.datax.protobuf.ProtobufColumn}
   */
  public static final class ProtobufColumn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.alibaba.datax.protobuf.ProtobufColumn)
      ProtobufColumnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtobufColumn.newBuilder() to construct.
    private ProtobufColumn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtobufColumn() {
      type_ = 0;
      rawData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtobufColumn();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtobufColumn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              rawData_ = input.readBytes();
              break;
            }
            case 24: {

              byteSize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufColumn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufColumn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.class, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder.class);
    }

    /**
     * Protobuf enum {@code com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType}
     */
    public enum ProtobufType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BAD = 0;</code>
       */
      BAD(0),
      /**
       * <code>NULL = 1;</code>
       */
      NULL(1),
      /**
       * <code>INT = 2;</code>
       */
      INT(2),
      /**
       * <code>LONG = 3;</code>
       */
      LONG(3),
      /**
       * <code>DOUBLE = 4;</code>
       */
      DOUBLE(4),
      /**
       * <code>STRING = 5;</code>
       */
      STRING(5),
      /**
       * <code>BOOL = 6;</code>
       */
      BOOL(6),
      /**
       * <code>DATE = 7;</code>
       */
      DATE(7),
      /**
       * <code>BYTES = 8;</code>
       */
      BYTES(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BAD = 0;</code>
       */
      public static final int BAD_VALUE = 0;
      /**
       * <code>NULL = 1;</code>
       */
      public static final int NULL_VALUE = 1;
      /**
       * <code>INT = 2;</code>
       */
      public static final int INT_VALUE = 2;
      /**
       * <code>LONG = 3;</code>
       */
      public static final int LONG_VALUE = 3;
      /**
       * <code>DOUBLE = 4;</code>
       */
      public static final int DOUBLE_VALUE = 4;
      /**
       * <code>STRING = 5;</code>
       */
      public static final int STRING_VALUE = 5;
      /**
       * <code>BOOL = 6;</code>
       */
      public static final int BOOL_VALUE = 6;
      /**
       * <code>DATE = 7;</code>
       */
      public static final int DATE_VALUE = 7;
      /**
       * <code>BYTES = 8;</code>
       */
      public static final int BYTES_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ProtobufType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ProtobufType forNumber(int value) {
        switch (value) {
          case 0: return BAD;
          case 1: return NULL;
          case 2: return INT;
          case 3: return LONG;
          case 4: return DOUBLE;
          case 5: return STRING;
          case 6: return BOOL;
          case 7: return DATE;
          case 8: return BYTES;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ProtobufType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ProtobufType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ProtobufType>() {
              public ProtobufType findValueByNumber(int number) {
                return ProtobufType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.getDescriptor().getEnumTypes().get(0);
      }

      private static final ProtobufType[] VALUES = values();

      public static ProtobufType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ProtobufType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType getType() {
      @SuppressWarnings("deprecation")
      com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType result = com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType.valueOf(type_);
      return result == null ? com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType.UNRECOGNIZED : result;
    }

    public static final int RAWDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rawData_;
    /**
     * <code>bytes rawData = 2;</code>
     * @return The rawData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawData() {
      return rawData_;
    }

    public static final int BYTESIZE_FIELD_NUMBER = 3;
    private int byteSize_;
    /**
     * <code>int32 byteSize = 3;</code>
     * @return The byteSize.
     */
    @java.lang.Override
    public int getByteSize() {
      return byteSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType.BAD.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!rawData_.isEmpty()) {
        output.writeBytes(2, rawData_);
      }
      if (byteSize_ != 0) {
        output.writeInt32(3, byteSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType.BAD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!rawData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rawData_);
      }
      if (byteSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, byteSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn)) {
        return super.equals(obj);
      }
      com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn other = (com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn) obj;

      if (type_ != other.type_) return false;
      if (!getRawData()
          .equals(other.getRawData())) return false;
      if (getByteSize()
          != other.getByteSize()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + RAWDATA_FIELD_NUMBER;
      hash = (53 * hash) + getRawData().hashCode();
      hash = (37 * hash) + BYTESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getByteSize();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alibaba.datax.protobuf.ProtobufColumn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alibaba.datax.protobuf.ProtobufColumn)
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufColumn_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufColumn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.class, com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.Builder.class);
      }

      // Construct using com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        rawData_ = com.google.protobuf.ByteString.EMPTY;

        byteSize_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alibaba.datax.protobuf.BufferOuterClass.internal_static_com_alibaba_datax_protobuf_ProtobufColumn_descriptor;
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn getDefaultInstanceForType() {
        return com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.getDefaultInstance();
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn build() {
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn buildPartial() {
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn result = new com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn(this);
        result.type_ = type_;
        result.rawData_ = rawData_;
        result.byteSize_ = byteSize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn) {
          return mergeFrom((com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn other) {
        if (other == com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getRawData() != com.google.protobuf.ByteString.EMPTY) {
          setRawData(other.getRawData());
        }
        if (other.getByteSize() != 0) {
          setByteSize(other.getByteSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType getType() {
        @SuppressWarnings("deprecation")
        com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType result = com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType.valueOf(type_);
        return result == null ? com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn.ProtobufType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.alibaba.datax.protobuf.ProtobufColumn.ProtobufType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rawData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rawData = 2;</code>
       * @return The rawData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRawData() {
        return rawData_;
      }
      /**
       * <code>bytes rawData = 2;</code>
       * @param value The rawData to set.
       * @return This builder for chaining.
       */
      public Builder setRawData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rawData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rawData = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawData() {
        
        rawData_ = getDefaultInstance().getRawData();
        onChanged();
        return this;
      }

      private int byteSize_ ;
      /**
       * <code>int32 byteSize = 3;</code>
       * @return The byteSize.
       */
      @java.lang.Override
      public int getByteSize() {
        return byteSize_;
      }
      /**
       * <code>int32 byteSize = 3;</code>
       * @param value The byteSize to set.
       * @return This builder for chaining.
       */
      public Builder setByteSize(int value) {
        
        byteSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 byteSize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearByteSize() {
        
        byteSize_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.alibaba.datax.protobuf.ProtobufColumn)
    }

    // @@protoc_insertion_point(class_scope:com.alibaba.datax.protobuf.ProtobufColumn)
    private static final com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn();
    }

    public static com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtobufColumn>
        PARSER = new com.google.protobuf.AbstractParser<ProtobufColumn>() {
      @java.lang.Override
      public ProtobufColumn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtobufColumn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtobufColumn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtobufColumn> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.alibaba.datax.protobuf.BufferOuterClass.ProtobufColumn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_datax_protobuf_Buffer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_datax_protobuf_Buffer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_datax_protobuf_ProtobufRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_datax_protobuf_ProtobufRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alibaba_datax_protobuf_ProtobufColumn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alibaba_datax_protobuf_ProtobufColumn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014buffer.proto\022\032com.alibaba.datax.protob" +
      "uf\"D\n\006Buffer\022:\n\006buffer\030\001 \003(\0132*.com.aliba" +
      "ba.datax.protobuf.ProtobufRecord\"s\n\016Prot" +
      "obufRecord\022;\n\007columns\030\001 \003(\0132*.com.alibab" +
      "a.datax.protobuf.ProtobufColumn\022\020\n\010byteS" +
      "ize\030\002 \001(\005\022\022\n\nmemorySize\030\003 \001(\005\"\347\001\n\016Protob" +
      "ufColumn\022E\n\004type\030\001 \001(\01627.com.alibaba.dat" +
      "ax.protobuf.ProtobufColumn.ProtobufType\022" +
      "\017\n\007rawData\030\002 \001(\014\022\020\n\010byteSize\030\003 \001(\005\"k\n\014Pr" +
      "otobufType\022\007\n\003BAD\020\000\022\010\n\004NULL\020\001\022\007\n\003INT\020\002\022\010" +
      "\n\004LONG\020\003\022\n\n\006DOUBLE\020\004\022\n\n\006STRING\020\005\022\010\n\004BOOL" +
      "\020\006\022\010\n\004DATE\020\007\022\t\n\005BYTES\020\010b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_alibaba_datax_protobuf_Buffer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alibaba_datax_protobuf_Buffer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_datax_protobuf_Buffer_descriptor,
        new java.lang.String[] { "Buffer", });
    internal_static_com_alibaba_datax_protobuf_ProtobufRecord_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alibaba_datax_protobuf_ProtobufRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_datax_protobuf_ProtobufRecord_descriptor,
        new java.lang.String[] { "Columns", "ByteSize", "MemorySize", });
    internal_static_com_alibaba_datax_protobuf_ProtobufColumn_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_alibaba_datax_protobuf_ProtobufColumn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alibaba_datax_protobuf_ProtobufColumn_descriptor,
        new java.lang.String[] { "Type", "RawData", "ByteSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
